### ISSUE TITLE
Godot crash when trying to load the sample scene

### ISSUE THREAD

**Issue by Armadon7** [arkology/ShaderV#7] opened 2021-03-12 21:51 UTC
Afternoon :) ,
When trying to load the sample scene in an open project to get a handle on setup etc. Godot full crashes. If I try to load it from the project selection window through the project.godot file that was uploaded it doesn't load and goes right back to the selection screen. I'm running Godot_v3.2.3-stable_x11.64 on Linux Mint 19.3.

**Comment by clemens-tolboom** [comment] 2021-03-19 16:15
Did you use the asserLib version or cloned this repo?

I did cloning this repo and open it as a Godot project without trouble on MacOS.

**Comment by Armadon7** [comment] 2021-03-27 01:54
I had Dled it as a zip from the repo, but I just dled it straight from the
godot's interface and it works totally fine through there


-- 

Michael Reisner, LMHC, CH

Reisner Counseling Services

243 Main St.
Suite #260
New Paltz, NY 12561

http://ReisnerCounselingServices.com

Phone: (845)-332-9500
Fax    : (845)-746-9092

Confidentiality Notice:  This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information.  Any unauthorized review, use, disclosure or
distribution is prohibited.  If you have received this communication in
error, please notify the sender immediately by replying to the message and
deleting it from your computer.

**Comment by VitalyS11** [comment] 2021-08-18 10:21
Can't reproduce on Windows 10, Godot_v3.3.2-stable_win64.
Is it still reproducible?

**Comment by arkology** [comment] 2021-08-18 10:25
Cannot reproduce on Windows 10, Godot 3.3.2 stable. Closing for now - if you still can reproduce the problem, fell free to comment, I'll try to do something.

**Closed by arkology** 2021-08-18 10:25 UTC
